# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 repositories:
   - repository: azure-templates-repo
     type: git
     name: jrebibo/azure-templates 

stages:
- template: stage-templates/maven-ubuntu-build-publish-stage.yml@azure-templates-repo
  paramaters:
    stage_name: 'build_and_publish'
    display_name: 'Build and Publish'
    maven_version: 'Default'
    artifact_name: 'mvn-jar-file'


- stage: security_scan
  displayName: Security Scan Stage
  jobs:
  - template: job-templates/sast-scan-job.yml@azure-templates-repo
  - template: job-templates/sca-scan-job.yml@azure-templates-repo
