trigger:
- main

pool:
  vmImage: 'windows-latest'

resources:
 repositories:
   - repository: azure-templates-repo
     type: git
     name: jrebibo/azure-templates 

stages:
- template: stage-templates/maven-ubuntu-build-publish-stage.yml@azure-templates-repo
  parameters:
    stage_name: 'maven_build_and_publish'
    display_name: 'Maven Build and Publish'


- stage: security_scan
  displayName: Security Scan Stage
  jobs:
  - template: job-templates/sast-scan-job.yml@azure-templates-repo
    parameters:
      job_name: 'static_application_security_testing'
      display_name: 'SAST Scan Job'
      scan_initiator: 'Azure Pipeline - spring-boot-hello-world-templated'
      application_name: 'jrebibo/spring-boot-hello-world'

  - template: job-templates/sca-scan-job.yml@azure-templates-repo
    parameters:
      job_name: 'software_composition_analysis'
      display_name: 'SCA Scan Job'
      scan_initiator: 'Azure Pipeline - spring-boot-hello-world-templated'
      application_name: 'jrebibo/spring-boot-hello-world'